#!/usr/bin/env node

var program = require('commander'),
    modpack = require('./app/modpack'),
    branch;

GLOBAL.runMode = "cli";

program
    .parse(process.argv);

branch = program.args;

modpack.createModPackFromBranch(branch);