#!/usr/bin/env node

var program = require('commander'),
    modpack = require('./app/modpack');

GLOBAL.runMode = "cli";

program
    .parse(process.argv);

tag = program.args;

modpack.createModPackFromTag(tag);