#!/usr/bin/env node

var program = require('commander');

program
    .version('0.0.1')
    .usage('<keywords>')
    .command('branch [name]', 'create from branch')
    .command('tag [version]', 'create from tag')
    .parse(process.argv);
